require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'rn' do
  config = use_native_modules!

  pod 'EXUpdatesInterface', path: '../node_modules/expo-updates-interface/ios/', :configurations => :debug
  pod 'expo-dev-menu-interface', path: '../node_modules/expo-dev-menu-interface', :configurations => :debug
  pod 'expo-dev-menu', path: '../node_modules/expo-dev-menu', :configurations => :debug
  pod 'expo-dev-launcher', path: '../node_modules/expo-dev-launcher', :configurations => :debug

  use_react_native!(:path => config["reactNativePath"])

  target 'rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 # use_flipper!
 # post_install do |installer|
 #   flipper_post_install(installer)
 #  end
end

target 'rn-tvOS' do
  # Pods for rn-tvOS

  target 'rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
