title: Navigate to the Deployment Pane
ref: navigate-to-the-deployment-pane
content: |
  To change your application's environment, navigate to to
  the :guilabel:`Deployment` pane through the {+leftnav+} and then
  click the :guilabel:`Environment` tab.
---
title: Select the Environment
ref: select-the-environment
content: |
  Select the environment for your app from the :guilabel:`Your Environment` 
  dropdown menu.

  .. figure:: /images/change-environment-select-environment.png
     :width: 750px
     :alt: The environment selection dropown menu
---
title: Save your Changes
ref: save-your-changes
content: |
  Press the :guilabel:`Save` button to set the new environment.

  If you have deployment drafts enabled, you'll need to review your draft
  and deploy to finalize the environment change. Press the :guilabel:`Review
  Draft & Deploy` button in the banner at the top of the UI. You'll see
  a summary of your changes. Click the :guilabel:`Deploy` button. 
