title: Pull the Latest Version of Your App
ref: pull-the-latest-version-of-your-app
content: |
  To configure a single-page application with {+cli-bin+}, you need a local copy
  of your application's configuration files.
  
  To pull a local copy of the latest version of your app, run the following:
  
  .. code-block:: bash
     
     realm-cli pull --remote="<Your App ID>"
  
  .. tip::
     
     You can also download a copy of your application's configuration files from
     the :guilabel:`Deploy > Import/Export App` screen in the {+ui+}.
---
title: Add Your Built Application Code
ref: add-your-built-application-code
content: |
  Single-page applications render in a single, specific HTML file,
  typically ``/index.html``. The file should include the necessary
  JavaScript code to wire up and render your application, either inline
  in a ``<script>`` tag or imported from an external file. You'll also
  need to host any resources that you don't intend to access through a
  CDN.
  
  When you are ready to host your SPA, run your application's build
  script and then copy the output build folder into the
  ``/hosting/files`` directory of your application directory.
---
title: Configure Realm to Serve Your Application
ref: configure-realm-to-serve-your-application
content: |
  In ``hosting/config.json``, set ``default_response_code`` to ``200`` and set
  ``default_error_path`` to the :ref:`resource path <hosting-resource-path>` of
  your SPA's root HTML file. Make sure to save the file when you're done.

  .. code-block:: json
     :caption: hosting/config.json
  
     {
       "enabled": true,
       "default_response_code": 200,
       "default_error_path": "/index.html",
     }
---
title: Deploy the Updated Hosting Configuration
ref: deploy-the-updated-hosting-configuration
content: |
  Once you've updated and saved ``hosting/config.json`` you can push the updated
  config to your remote app. {+cli+} immediately supports your SPA on push.
  
  .. code-block:: bash
     
     realm-cli push --remote="<Your App ID>" --include-hosting
...
