title: Navigate to the {+sync-short+} Configuration Screen
ref: navigate-to-the-{+sync-short+}-configuration-screen
content: |
  To define {+sync-short+} rules and enable {+sync-short+} for your application, navigate to the
  :guilabel:`{+sync-short+}` configuration screen through the {+leftnav+}.

  .. note:: {+sync-short+} Rules Cannot Change
     
     You define {+sync-short+} rules at the same time as you enable {+sync-short+}. Once {+sync-short+} is
     enabled, you can't change your app's {+sync-short+} rules unless you terminate {+sync-short+}
     and re-enable it with new rules.
---
title: Select Development Details
ref: select-development-details
content: |
  You can configure various development details under the :guilabel:`Select
  Development Details` heading, such as {+sync-short+} types, development mode,
  and a cluster to {+sync-short+}.

  Below the :guilabel:`{+sync-short+} types` subheading, select the :guilabel:`Flexible`
  option to enable Flexible {+sync-short+} and send queries from a client using a set of
  queryable fields. 
  
  Next, under the :guilabel:`Development Mode` subheading, you can choose to
  toggle :ref:`development mode <enable-disable-development-mode>` on/off.
  Enabling ``Development Mode`` allows you to define schemas directly in your
  client application code and is suitable if you are in development and do not
  have application data in Atlas yet.
  
  Finally, you can enable {+sync-short+} for a single :term:`linked cluster` in your
  application. Determine which cluster you want to use and select it from
  the :guilabel:`Select Cluster To {+sync-short+}` dropdown menu.

  .. figure:: /images/flex-sync-select-development-details.png
     :width: 750px
     :alt: Select Development Details Menu
---
title: Select Queryable Fields
ref: select-queryable-fields
content: |
  When configuring Flexible {+sync-short+}, specify one or more fields from your
  {+sync-short+} Schema that your client application can query. 
  
  To configure queryable fields for your application, navigate to the
  :guilabel:`Select Queryable Fields` heading. Select up to 10 existing fields
  from your schema to query on. If you wish to create a new field(s) to
  construct a query on, you must define a database and enable ``Development Mode``.

  .. figure:: /images/flex-sync-set-queryable-fields.png
     :width: 750px
     :alt: Select Queryable Fields
---
title: Define Read & Write Permissions
ref: define-read-write-permissions
content: |
  The :guilabel:`Define Permissions` section allows you to define :ref:`JSON
  expressions <expressions>` that {+service+} dynamically evaluates to determine a
  user's read and write permissions for the data in a given partition.
  
  {+sync-short+} rule expressions have access to :json-expansion:`%%user`, which resolves
  to the user that opened the {+realm+}, and :json-expansion:`%%partition`, which
  resolves to the partition key value for the {+realm+}. You can also use operators,
  including :json-operator:`%function`, to handle more complex cases. For
  examples, see :ref:`{+sync-short+} Permissions <sync-permissions>`.

  Once you've determined how to decide a user's read and write permissions for a
  given partition, define the corresponding JSON expressions in the
  :guilabel:`Read` and :guilabel:`Write` inputs.
  
  .. figure:: /images/flex-sync-define-permissions.png
     :width: 750px
     :alt: Define Permissions Settings
---
title: Turn On Sync
ref: turn-on-sync
content: |
  Now that you've configured rules for your synced cluster, all that's left to
  do is turn on {+sync-short+} for client applications. Click :guilabel:`Enable {+sync-short+}`,
  take note of any recommendations that appear, and then confirm your choice.

