title: Navigate to the Authentication Provider Configuration Screen
ref: navigate-to-the-authentication-provider-configuration-screen
content: |
  You can configure and enable user metadata in the {+ui+}. To
  get to the configuration page:
  
  - Click :guilabel:`Authentication` in the {+leftnav+}.
  - Select the :guilabel:`Authentication Providers` tab. 
  - Press the :guilabel:`EDIT` button for the provider whose metadata
    you want to configure.
---
title: Configure User Metadata
ref: configure-user-metadata
content: |

  **Google or Facebook**

  Select the checkboxes next to the metadata fields you want to enable.
  
  .. figure:: /images/configure-user-metadata-google-facebook-realm-ui.png
     :alt: The checkboxes to enable user metadata fields in the {+ui+}
     :width: 750px
     :lightbox:

  **Custom JWT Authentication**

  You can specify the metadata fields that your identity provider supports. 
  After you press the :guilabel:`Add Field` button, define:

  - The path
  - The field name
  - Whether the field is optional or required

  For more details, see: :ref:`JWT metadata fields 
  <custom-jwt-authentication-configuration-metadata-fields>`.

  .. figure:: /images/configure-user-metadata-custom-jwt-realm-ui.png
     :alt: Add metadata required/optional, path, and name in the {+ui+}
     :width: 750px
     :lightbox:
  
  After you configure the metadata you want to access, press 
  the :guilabel:`Save Draft` button.
---
title: Deploy the Updated Application
ref: deploy-the-updated-application
content: |
  After you update the metadata configuration, you must deploy your 
  application. To deploy a draft application from the {+ui+}:
  
  1. Click :guilabel:`Deploy` in the {+leftnav+}.
  
  2. Find the draft in the deployment history table and then click
     :guilabel:`Review & Deploy Changes`.
  
  3. Review the diff of changes and then click :guilabel:`Deploy`.

  Once the application successfully deploys, {+service-short+} begins to associate
  metadata with users. When a user logs in, {+service-short+} requests user
  permission to access the requested metadata. If the user approves, 
  {+service-short+} exposes the data in that user's :ref:`user object 
  <user-objects>`.
...
