title: Navigate to the File in the File Tree
ref: navigate-to-the-file-in-the-file-tree
content: |
  To add a metadata attribute to a specific file you need to find the
  file in the hosted file tree. To find the file:

  1. Click :guilabel:`Hosting` in the {+leftnav+}.

  2. Select the :guilabel:`Files` tab.

  3. Find the entry for the file in the file tree.
---
title: Add a New Attribute
ref: add-a-new-attribute
content: |
  Once you have found the file, you need to add a new metadata
  attribute to it. To add a new metadata attribute:

  1. Click the file's :guilabel:`Actions (...)` button.

  2. Click :guilabel:`Edit Attributes...`

  3. In the :guilabel:`Set Attributes` modal, click :guilabel:`Add
     Attribute`.
---
title: Select the Attribute Type and Value
ref: select-the-attribute-type-and-value
content: |
  The new metadata attribute will not have a type or value when you
  first add it.

  1. Select the attribute type from new attribute's left-hand dropdown

  2. Enter a value for the attribute in the right-hand input box.

  3. Click :guilabel:`Save`.
...
