title: Navigate to the Sync Configuration Screen
ref: navigate-to-the-sync-configuration-screen
content: |
  To define sync rules and enable sync for your application, navigate to the
  :guilabel:`Sync` configuration screen through the {+leftnav+}.

  .. note:: Sync Rules Cannot Change
     
     You define sync rules at the same time as you enable sync. Once sync is
     enabled, you can't change your app's sync rules unless you terminate sync
     and re-enable it with new rules.
---
title: Select Development Details
ref: select-development-details
content: |
  Under the guilabel:`Select Development Details` heading you can configure various 
  development details, such as sync types, development mode, and a cluster to sync. 

  Below the :guilabel:`sync types` subheading, select the :guilabel:`Flexible`
  option to enable Flexible Sync and send queries from a client using a set of
  queryable fields. 
  
  Next, under the :guilabel:`Development Mode` subheading you can choose to
  toggle :ref:`development mode <enable-disable-development-mode>` on or of.
  Enabling ``Development Mode`` allows you to define schemas directly in your
  client application code and may be suitable if you in development and do not
  have application data in Atlas yet.
  
  Finally, you can enable sync for a single :term:`linked cluster` in your
  application. Determine which cluster you want to use and then select it from
  the :guilabel:`Select Cluster To Sync` dropdown menu.

  .. figure:: /images/flex-sync-select-development-details.png
     :width: 750px
     :alt: Select Development Details Menu
---
title: Select Queryable Fields
ref: select-queryable-fields
content: |
  When you configure Flexible Sync, you specify one or more fields from your
  Sync Schema that your client application can query. 
  
  To configure queryable fields for your application, navigate to the
  :guilabel:`Select Queryable Fields` heading. Select up to 10 existing fields
  from your schema to query on. If you wish to create a new field(s) to
  construct a query on, ``Development Mode`` must be enabled, and you must
  define a database. 

  .. figure:: /images/flex-sync-set-queryable-fields.png
     :width: 750px
     :alt: Select Queryable Fields
---
title: Define Read & Write Permissions
ref: define-read-write-permissions
content: |
  The :guilabel:`Define Permissions` section allows you to define :ref:`JSON
  expressions <expressions>` that Realm dynamically evaluates to determine a
  user's read and write permissions for the data in a given partition.
  
  Sync rule expressions have access to :json-expansion:`%%user`, which resolves
  to the user that opened the realm, and :json-expansion:`%%partition`, which
  resolves to the partition key value for the realm. You can also use operators,
  including :json-operator:`%function`, to handle more complex cases. For
  examples, see :ref:`Sync Permissions <sync-permissions>`.

  Once you've determined how to decide a user's read and write permissions for a
  given partition, define the corresponding JSON expressions in the
  :guilabel:`Read` and :guilabel:`Write` inputs.
  
  .. figure:: /images/flex-sync-define-permissions.png
     :width: 750px
     :alt: Define Permissions Settings
---
title: Turn On Sync
ref: turn-on-sync
content: |
  Now that you've configured rules for your synced cluster, all that's left to
  do is turn on sync for client applications. Click :guilabel:`Enable Sync`,
  take note of any recommendations that appear, and then confirm your choice.

