title: Pull the Latest Version of Your App
ref: pull-the-latest-version-of-your-app
content: |
  To update your app with {+cli-bin+}, you need a local copy of its 
  configuration files.
  
  To pull a local copy of the latest version of your app, run the following:
  
  .. code-block:: bash
     
     realm-cli pull --remote="<Your App ID>"
  
  .. tip::
     
     You can also download a copy of your application's configuration files from
     the {+ui+}. Go to the :guilabel:`Deploy > Export App` screen from
     the Realm Application Dashboard.
---
title: Configure User Metadata
ref: configure-user-metadata
content: |
  You can find authentication provider :ref:`metadata_fields 
  <config-auth-providers>` for your app in ``/auth/providers.json``. 
  Update this array to request user metadata from the authentication provider.

  **Google or Facebook**

  This array resembles:

  .. code-block:: javascript
     :caption: /auth/providers.json
     
     { ...other config details...
       "metadata_fields": [
         {
           "required": false,
           "name": "name"
         },
         {
           "required": false,
           "name": "gender"
         }
       ]
     }

  **Custom JWT authentication** 
  
  The metadata_fields array has an additional property, ``field_name``. 
  In custom JWT authentication, ``name`` represents the path to the field. 
  The ``field_name`` represents the name of the field.

  .. code-block:: javascript
     :caption: /auth/providers.json
     
     { ...other config details...
       "metadata_fields": [
         {
           "required": true,
           "name": "user.name",
           "field_name": "name"
         },
         {
           "required": false,
           "name": "user.favoriteColor",
           "field_name": "favoriteColor"
         }
       ]
     }

---
title: Deploy the Custom User Data Configuration
ref: deploy-the-custom-user-data-configuration
content: |
  Once you've configured custom user data, you can push the updated config to
  your remote app. {+cli+} immediately deploys the update on push.
  
  .. code-block:: bash
     
     realm-cli push --remote="<Your App ID>"
