/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  java: [
    "intro",
    "install",
    "quick-start",
    {
      type: "category",
      label: "Realm Database",
      collapsible: true,
      collapsed: false,
      items: [
        "realm-database/overview",
        "realm-database/async-api",
        {
          type: "category",
          label: "Realms",
          collapsible: true,
          collapsed: true,
          items: [
            "realm-database/realms/overview",
            "realm-database/realms/open-and-close-a-realm",
            "realm-database/realms/bundle-a-realm",
            "realm-database/realms/encrypt-a-realm",
          ],
        },
        {
          type: "category",
          label: "Create",
          collapsible: true,
          collapsed: true,
          items: ["realm-database/create/create-a-new-object"],
        },
        {
          type: "category",
          label: "Read",
          collapsible: true,
          collapsed: true,
          items: [
            "realm-database/read/find-object-by-primary-key",
            "realm-database/read/find-objects-of-a-type",
            "realm-database/read/sort-queries",
            "realm-database/read/iteration",
          ],
        },
        {
          type: "category",
          label: "Update",
          collapsible: true,
          collapsed: true,
          items: [
            "realm-database/update/modify-an-object",
            "realm-database/update/upsert-an-object",
            "realm-database/update/update-a-collection",
          ],
        },
        {
          type: "category",
          label: "Delete",
          collapsible: true,
          collapsed: true,
          items: [
            "realm-database/delete/delete-an-object",
            "realm-database/delete/delete-multiple-objects",
            "realm-database/delete/delete-all-objects-of-a-type",
            "realm-database/delete/delete-all",
          ],
        },
        {
          type: "category",
          label: "Schemas",
          collapsible: true,
          collapsed: true,
          items: [
            "realm-database/schemas/overview",
            {
              type: "category",
              label: "Data Types",
              collapsible: true,
              collapsed: true,
              items: [
                "realm-database/schemas/data-types/supported-types",
                "realm-database/schemas/data-types/collections",
                "realm-database/schemas/data-types/counters",
                "realm-database/schemas/data-types/enums",
                "realm-database/schemas/data-types/embedded-objects",
                "realm-database/schemas/data-types/realm-any",
                "realm-database/schemas/data-types/realm-dictionary",
                "realm-database/schemas/data-types/realm-set",
              ],
            },
            "realm-database/schemas/relationships",
            "realm-database/schemas/versions-and-migrations",
          ],
        },
        "realm-database/filter-data",
        "realm-database/query-language",
        "realm-database/write-transactions",
        "realm-database/notifications",
        "realm-database/freeze-objects",
      ],
    },
    {
      type: "category",
      label: "App Services",
      collapsible: true,
      collapsed: true,
      items: [
        "app-services/overview",
        "app-services/connect",
        {
          type: "category",
          label: "Users",
          collapsible: true,
          collapsed: true,
          items: [
            "app-services/users/authenticate-users",
            "app-services/users/user-api-keys",
            "app-services/users/email-password-users",
            "app-services/users/custom-user-data",
            "app-services/users/link-users",
            "app-services/users/multi-user-applications",
          ],
        },
        {
          type: "category",
          label: "Sync",
          collapsible: true,
          collapsed: true,
          items: [
            "app-services/sync/overview",
            "app-services/sync/quick-start",
            "app-services/sync/open-a-synced-realm",
            "app-services/sync/reset-a-client-realm",
            "app-services/sync/flexible-sync",
            "app-services/sync/manual-client-reset-data-recover",
          ],
        },
        "app-services/functions",
        {
          type: "category",
          label: "Query MongoDB",
          collapsible: true,
          collapsed: true,
          items: [
            "app-services/mongodb/overview",
            "app-services/mongodb/create",
            "app-services/mongodb/read",
            "app-services/mongodb/update",
            "app-services/mongodb/delete",
            "app-services/mongodb/watch",
            "app-services/mongodb/aggregate",
          ],
        },
      ],
    },
    {
          type: "category",
          label: "Best Practices",
          collapsible: true,
          collapsed: true,
          items: [
            "best-practices/android-livedata",
            "best-practices/threading",
            "best-practices/testing",
            "best-practices/logging",
            "best-practices/troubleshooting",
          ],
        },
    
    {
      type: "link",
      label: "Release Notes",
      href: "https://github.com/realm/realm-java/blob/releases/CHANGELOG.md",
    },
    {
      type: "link",
      label: "API Reference",
      href: "https://docs.mongodb.com/realm/api/",
    },
  ],
};

module.exports = sidebars;
