git:
  remote:
    upstream: 'mongodb/docs-realm'
    tools: 'mongodb/docs-tools'
project:
  name: 'realm'
  tag: 'realm'
  url: 'http://docs.mongodb.com/realm'
  title: "MongoDB Realm"
  branched: false
system:
  make:
    generated:
      - 'meta'
      - 'integration'
      - 'sphinx'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
      - 'makefile.dtf'
  files:
    - 'htaccess.yaml'
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'push.yaml'
    - 'sphinx_local.yaml'
version:
  release: '2.6.4'
  branch: '2.6'
assets:
  - branch: master
    path: build/docs-tools
    repository: http://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
