project: 'realm'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'realm'
  project: 'realm'
  sitename: 'MongoDB Realm'
  jira: 'DOCSP'
  sitename: 'MongoDB Realm'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /data-model
    - /mongodb-realm
    - /mongodb/crud-snippets
sidebars:
  '**':
    - 'pagenav.html'
...
