included:
- Examples/
- HostApp/
- QuickStarSwiftUI/

disabled_rules:
- force_try
- line_length
- type_name
- function_body_length
- unused_closure_parameter
- unused_capture_list
- unused_enumerated
- unused_optional_binding

identifier_name:
  excluded:
    - id
    - _id
    - _partition
    - YOUR_REALM_APP_ID

