platform :ios, '13.0'

target 'RealmExamples' do
  use_frameworks!
  pod 'Realm', '=10.1.0'
  pod 'RealmSwift', '=10.1.0'
end

target 'QuickStartSwiftUI' do
  use_frameworks!

  pod 'RealmSwift', '=10.1.0'
end

