platform :ios, '15.0'

target 'RealmExamples' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'Realm', :git => 'https://github.com/realm/realm-swift.git', :branch => 'dp/flexible_sync_v1.0.0'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-swift.git', :branch => 'dp/flexible_sync_v1.0.0'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit', '=8.1.0'
end

target 'QuickStartSwiftUI' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-swift.git', :branch => 'dp/flexible_sync_v1.0.0'
end

target 'SwiftUIExamples' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-swift.git', :branch => 'dp/flexible_sync_v1.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
