platform :ios, '13.0'

target 'RealmExamples' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :branch => 'py/dictionary'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'py/dictionary'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit', '=8.1.0'
end

target 'QuickStartSwiftUI' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'py/dictionary'
end
