[[facets]]
category = "programming_language"
value = "javascript/typescript"

[[facets]]
category = "target_product"
value = "realm"

[[facets.sub_facets]]
category = "sub_product"
value = "react-native"
