name: C++ Example Tests

on:
  pull_request:
    paths:
      - "examples/cpp/sync/**"

jobs:
  tests:
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3
        run: |
          cd examples/cpp/sync
          mkdir build && cd build
          cmake ..
          cmake --build .
          ./examples-sync
