name: C++ Example Tests

on:
  pull_request:
    paths:
      - "examples/cpp/**"

jobs:
  build:
    name: Run C++ Example Tests
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd examples/cpp
          mkdir build && cd build
          cmake ..
          make
          ./examples
