name: Check All Links for Errors

on:
  push:
    paths:
      - "source/**"

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with: 
          go-version: '1.20.6'
          cache-dependency-path: go.sum
      - uses: MongoCaleb/checker@main
