name: Find Unused Files

on:
  pull_request:
    paths:
      - "source/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cbush/docdoctor/actions/find-unused@find-unused-action
        with:
          source: ./source
