name: Android CI Realm Example App

on:
  pull_request:
    paths:
      - 'examples/java/**'

jobs:
  build_sync:
    name: Run Android Example App Tests (Sync)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: cd examples/java/sync && ./gradlew connectedAndroidTest || ./gradlew connectedAndroidTest

  build_local:
    name: Run Android Example App Tests (Local)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: cd examples/java/local && ./gradlew test && ./gradlew connectedAndroidTest || ./gradlew connectedAndroidTest
