name: Node.js SDK Legacy CI Tests

on:
  pull_request:
    paths:
      - "examples/node/legacy/**"

jobs:
  build:
    name: Run Node.js SDK Legacy Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: examples/node/legacy
        run: npm install
      - name: Test JavaScript
        working-directory: examples/node/legacy
        run: npm run test:js
      - name: Test TypeScript
        working-directory: examples/node/legacy
        run: npm run test:ts
