name: Push to Artifact Repos

# https://github.com/mongodb-university/realm-tutorial-react-native.git
# https://github.com/mongodb-university/realm-tutorial-backend
# https://github.com/mongodb-university/realm-tutorial-web
# https://github.com/mongodb-university/realm-tutorial-node-js
# https://github.com/mongodb-university/realm-tutorial-ios-swift
# https://github.com/mongodb-university/realm-tutorial-android-kotlin
# https://github.com/mongodb-university/realm-tutorial-dotnet

on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/push-to-artifact-repo
        with:
          source: ./tutorial/rn
          state: start
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-react-native.git
      - uses: ./github/actions/push-to-artifact-repo
        with:
          source: ./tutorial/rn
          state: final
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-react-native.git
