name: Push to Artifact Repos

on:
  push:
    branches:
      - master
    paths:
      - "tutorial/**"

jobs:
  check:
    name: Bluehawk Check Tutorials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npx bluehawk check -i "*.md" -i "*.properties" -i "*.lock" tutorial
  push:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Web
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start final
          source: ./tutorial/web
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-web.git
          commitMessage: Update

            Initiated by https://github.com/mongodb/docs-realm/commit/${{ github.sha }}
      - name: Backend
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: final
          source: ./tutorial/backend
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-backend.git
          commitMessage: Update

            Initiated by https://github.com/mongodb/docs-realm/commit/${{ github.sha }}

      - name: Unity
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start local sync
          source: ./tutorial/unity
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-unity
          commitMessage: Update

            Initiated by https://github.com/mongodb/docs-realm/commit/${{ github.sha }}
