name: Push to Artifact Repos

# TODO: change this to push to master branch only (and update to tutorial/**)
on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: React Native
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start final
          source: ./tutorial/rn
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-react-native.git
            - name: iOS/Swift
              uses: ./.github/actions/push-to-artifact-repo
              with:
                email: chris.bush+arty-fact@mongodb.com
                name: Arty Fact
                states: start final
                source: ./tutorial/swift-ios
                toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-ios-swift.git
      - name: Web
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start final
          source: ./tutorial/web
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-web.git
      - name: Node.js
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start final
          source: ./tutorial/node-cli
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-node-js.git
      - name: Android/Kotlin
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: start final
          source: ./tutorial/kotlin-android
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-android-kotlin.git
      - name: Backend
        uses: ./.github/actions/push-to-artifact-repo
        with:
          email: chris.bush+arty-fact@mongodb.com
          name: Arty Fact
          states: final # note: backend does not currently use states
          source: ./tutorial/backend
          toRepo: https://${{ secrets.TUTORIAL_REPO_ACCESS_TOKEN }}@github.com/mongodb-university/realm-tutorial-backend.git
# TODO: dotnet (arty-fact machine user does not currently have access)
